const LOGIN_ERROR = 100;
const SINGNUP_ERROR = 110;
const ACCESS_DENIED = 120;
const CREATEING_ERROR = 130;
const NOT_FOUND = 140;
const ALREADY_EXISTS = 150;
const VERVIFICATION_CODE_ERROR = 160;
const EMAIL_ERROR = 170;
const INVALID_TOKEN = 401;
export {
  LOGIN_ERROR,
  SINGNUP_ERROR,
  ACCESS_DENIED,
  CREATEING_ERROR,
  NOT_FOUND,
  ALREADY_EXISTS,
  EMAIL_ERROR,
  VERVIFICATION_CODE_ERROR,
  INVALID_TOKEN,
};
